// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Usm = newAsset("usm.c", "b22abd33a5742946d6cddcb203fac46ca1fa1d8521df8cc81f5f6660bf19fbe1")
